version: '3.8'

services:
  # backend:
  #   image: ${FUSION_REST_APP_IMAGE}:1
  #   environment:
  #     FUSIONAUTH_URL: ${FUSIONAUTH_URL}
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - poc1_net

  frontend:
    image: ${FUSION_REACT_APP_IMAGE}:1
    ports:
      - "3000:3000"
    networks:
      - poc1_net
    
networks:
  poc1_net:
    driver: bridge